service: rekobot

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: eu-west-1
  environment:
    PAGE_LOAD_TIMEOUT: 20000
    LOGGING: true

plugins:
  - serverless-plugin-chrome

custom:
  chrome:
    flags:
      - --interpreter none
      - --headless
      - --disable-gpu
      - --disable-translate
      - --disable-extensions
      - --disable-background-networking
      - --safebrowsing-disable-auto-update
      - --disable-sync
      - --metrics-recording-only
      - --disable-default-apps
      - --no-first-run
      - --mute-audio
      - --hide-scrollbars
      - --remote-debugging-port=9222
    functions:
      - expense

functions:
  expense:
    description: takes an expense as json and converts it to a pdf
    memorySize: 1536
    timeout: 10
    handler: src/expense/handler.handler
    events:
      - http:
          path: expense
          method: post

resources:
  Resources:
    ApiGatewayRestApi:
      Properties:
        BinaryMediaTypes:
          - application/pdf